# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define :windows do |c|
    c.vm.hostname = "windows-server"
    c.vm.box = "windows-2012R2"

    # Forward rdp
    c.vm.network :forwarded_port, guest: 3389, host: 3389

    # We share the source folder with smb
  end

end
